<?php
    /** @var $engravingHelper \MemorialBracelets\EngravingDisplay\Helper\Data */
    $engravingHelper = $this->helper('MemorialBracelets\EngravingDisplay\Helper\Data');

    $_item = $block->getItem();
    $pOptions = $_item->getOrderItem()->getProductOptions();
    unset($pOptions['additional_options']);

    //Add wording to engraving lines.
    if (isset($pOptions['options'])) {
        foreach ($pOptions['options'] as $k => $opt) {
            if ($opt['option_type'] == 'engraving') {
                $text = trim($opt['print_value']);
                $text .= "\n* " . $engravingHelper->getEngravingMessage();
                $opt['print_value'] = $text;
                $opt['value'] = $text;
                $pOptions['options'][$k] = $opt;
            }
        }
    }
    $_item->getOrderItem()->setProductOptions($pOptions);
?>
<tr>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= /* @escapeNotVerified */  __('SKU'); ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()): ?>
            <dl class="item-options">
                <?php foreach ($block->getItemOptions() as $option): ?>
                    <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                    <dd>
                        <?= /* @escapeNotVerified */  nl2br($option['value']) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-qty"><?= /* @escapeNotVerified */  $_item->getQty() * 1 ?></td>
</tr>
