beta.memorialbracelets.info:
  stage: develop
  branch: master
  deploy_path: /home/cedutktf/Magento
  hostname: us-wpl-c8-km104.wpl.host
  port: 87
  http_user: cedutktf
  user: cedutktf
  extra_param: "beta.memorialbracelets.info"
