<?php
/**
 * Send to friend form
 *
 * @var $block \Magento\SendFriend\Block\Send
 */
?>
<script id="add-recipient-tmpl" type="text/x-magento-template">
    <div class="actions-toolbar">
        <div class="secondary">
            <button type="button" id="btn-remove<%- data._index_ %>" class="action remove"
                    title="<?= $block->escapeJsQuote(__('Remove Recipent')) ?>">
                <span><?= $block->escapeJsQuote(__('Remove')) ?></span>
            </button>
        </div>
    </div>
    <fieldset class="fieldset">
        <div class="field name required">
            <label for="recipients-name<%- data._index_ %>" class="label"><span><?= __('Name')?></span></label>
            <div class="control">
                <input name="recipients[name][<%- data._index_ %>]" type="text" title="<?= __('Name') ?>" class="input-text"
                       id="recipients-name<%- data._index_ %>" data-validate="{required:true}"/>
            </div>
        </div>

        <div class="field email required">
            <label for="recipients-email<%- data._index_ %>" class="label"><span><?= __('Email') ?></span></label>
            <div class="control">
                <input name="recipients[email][<%- data._index_ %>]" title="<?= __('Email') ?>"
                       id="recipients-email<%- data._index_ %>" type="email" class="input-text"
                       data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
    </fieldset>
</script>

<form action="<?= $block->getSendUrl() ?>" method="post" id="product-sendtofriend-form"
      data-mage-init='{
        "rowBuilder":{
            "rowTemplate":"#add-recipient-tmpl",
            "rowContainer":"#recipients-options",
            "rowParentElem":"<div></div>",
            "remEventSelector":"button",
            "btnRemoveSelector":".action.remove",
            "maxRows":"<?= $block->getMaxRecipients() ?>",
            "maxRowsMsg":"#max-recipient-message",
            "addRowBtn":"#add-recipient-button",
            "additionalRowClass":"additional"},
        "validation":{}}'
      class="form send friend" data-hasRequired="<?= __('* Required Fields') ?>">
    <?php if ($block->getData('isAjax')): ?>
        <?php $test = '' ?>
        <input name="isAjax" value="1" type="hidden"/>
    <?php endif ?>
    <fieldset class="fieldset sender" id="sender_options">
        <?= $block->getBlockHtml('formkey')?>
        <legend class="legend"><span><?= __('Sender') ?></span></legend>
        <br>
        <div class="field sender required">
            <label for="sender-name" class="label"><span><?= __('Name') ?></span></label>
            <div class="control">
                <input name="sender[name]" value="<?= $block->escapeHtml($block->getUserName()) ?>"
                       title="<?= __('Name') ?>" id="sender-name" type="text" class="input-text"
                       data-validate="{required:true}"/>
            </div>
        </div>

        <div class="field email required">
            <label for="sender-email" class="label"><span><?= __('Email') ?></span></label>
            <div class="control">
                <input name="sender[email]" value="<?= $block->escapeHtml($block->getEmail()) ?>"
                       title="<?= __('Email') ?>" id="sender-email" type="text" class="input-text"
                       data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>

        <div class="field text required">
            <label for="sender-message" class="label"><span><?= __('Message') ?></span></label>
            <div class="control">
                <textarea name="sender[message]" class="input-text" id="sender-message" cols="3" rows="3"
                          data-validate="{required:true}"><?= $block->escapeHtml($block->getMessage()) ?></textarea>
            </div>
        </div>
    </fieldset>

    <fieldset class="fieldset recipients">
        <?= $block->getBlockHtml('formkey')?>
        <legend class="legend"><span><?= __('Invitee') ?></span></legend>
        <br />
        <div id="recipients-options"></div>
        <?php if ($block->getMaxRecipients()): ?>
            <div id="max-recipient-message" style="display: none;" class="message notice limit" role="alert">
                <span><?= __('Maximum %1 email addresses allowed.', $block->getMaxRecipients()) ?></span>
            </div>
        <?php endif; ?>
        <div class="actions-toolbar">
            <div class="secondary">
                <?php if (1 < $block->getMaxRecipients()): ?>
                    <button type="button" id="add-recipient-button" class="action add invitee-add">
                        <span><?= __('Add Invitee') ?></span></button>
                <?php endif; ?>
            </div>
            <div class="primary">
                <button type="submit"
                        class="action submit primary"<?php if (!$block->canSend()): ?> disabled="disabled"<?php endif ?>>
                    <span><?= __('Send Email') ?></span></button>
            </div>
            <div class="back-link">
                <a class="action back" href="#" role="back"><span><?= __('Back') ?></span></a>
            </div>
        </div>
    </fieldset>
</form>

<script type="text/x-magento-init">
    {
        "a[role='back']": {
            "Magento_SendFriend/back-event": {}
        }
    }
</script>
<?php if ($block->getData('isAjax')): ?>
    <script>
        require([
            'jquery',
            'domReady!'
        ], function ($) {
            $(document).ready(function () {
                $(document).on('submit', '#product-sendtofriend-form', function(event) {
                    event.preventDefault();
                    var target = $('#email-friend-container');

                    $.ajax({
                        url: $(this).attr('action'),
                        type: $(this).attr('method'),
                        dataType: 'json',
                        showLoader: true,
                        cache: false,
                        data: $(this).serialize(),
                        success : function(response) {
                            if (response.output) {
                                $(target).hide('fast');
                                $(target).find('.content').empty();
                            }
                        }
                    });
                });
            });
        });
    </script>
<?php endif ?>
