<?php $product     = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php $qtyBlock    = $block->getLayout()->getBlock('quantity-discounts')?>
<?php if ($product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= __('Qty') ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= __('Qty') ?>" class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button"><i class="icon-add-to-cart"></i>
                <span><?= $buttonTitle ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
    <?php // skip quantity discounts block for gift card items ?>
    <?php if(!$type = $product->getTypeId() === 'aw_giftcard'): ?>
        <div class="quantity-discount-wrapper">
            <a class="link" id="discount-anchor"
               title="<?= __('Click to Display Discounts') ?>"><i class="icon-question-mark"></i><?= __('Quantity Discounts') ?></a>
            <div class="discount-content">
                <div class="table-wrapper">
                    <?= ($qtyBlock) ? $qtyBlock->toHtml() : '' ?>
                </div>
                <div class="arrow"></div>
            </div>
        </div>
    <?php endif ?>
</div>
<div class="ajax-messages"></div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "catalogAddToCart": {
                    "bindSubmit": true
                }
            }
        }
    </script>
<?php endif; ?>
