<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/
?>
<?php
$_product = $block->getProduct();
$_wishlistSubmitParams = $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product);
$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');

/** Check if product type is giftcard type. */
$applyChanges = false;
$isGiftcardType = ($_product->getData('type_id') == 'aw_giftcard') ? true : false;
if (isset($isGiftcardType) && $isGiftcardType) {
    /** @var  $applyChanges, if product type is giftcard, set flag to apply style changes. */
    $applyChanges = true;
}
?>

<?php if (!$applyChanges) : ?>
    <div class="product-addto-links" data-role="add-to-links">
        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
            <a href="#" class="action towishlist" id="product-addtowishlist-action">
                <i class="icon-wishlist"></i>
                <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
            </a>
        <?php endif; ?>
        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product);?>'
            data-role="add-to-links"
            class="action tocompare"><i class="icon-compare"></i><span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span></a>
    </div>
    <script type="text/x-magento-init">
        {
            "body": {
                "addToWishlist": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getWishlistOptions())?>
            },
            "#product-addtowishlist-action": {
                "MemorialBracelets_NameProduct/js/product-to-wish-list": {}
            }
        }
</script>
<?php endif; ?>