<?php
?>

<script type="text/javascript">
    // <![CDATA[
    require([
            "IWD_OrderManager/js/creditmemo/view/info",
            "prototype"
        ],
        function(iwdOrderManagerCreditmemoInfo) {
            var orderManagerCreditmemoInfo = new iwdOrderManagerCreditmemoInfo();
            orderManagerCreditmemoInfo.init(<?php echo $block->jsonParamsCreditmemoInfo(); ?>);
        }
    );
    // ]]>
</script>