<?php
/** @var $block \Aheadworks\Giftcard\Block\Product\View */
?>
<?php
$_product = $block->getProduct();
?>

<div class="product-add-form aw-gc-product-add-form">
    <form action="<?php echo $block->getSubmitUrl($_product) ?>" method="post"
          id="product_addtocart_form" enctype="multipart/form-data"
          data-role="aw-gift-card-product-form"
          data-bind="scope: 'product_addtocart_form'">
        <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
        <?php echo $block->getBlockHtml('formkey')?>
        <div data-bind="blockLoader: isLoading">
            <?php echo $block->getChildHtml('form_top'); ?>
            <?php echo $block->getChildHtml('giftcard_description'); ?>
            <?php echo $block->getChildHtml('giftcard_options'); ?>
            <?php echo $block->getChildHtml('product_info_form_content'); ?>
        </div>
    </form>
    <script type="text/x-magento-init">
    {
        "[data-role=aw-gift-card-product-form]": {
            "Magento_Ui/js/core/app": <?php echo $block->getJsLayout();?>,
            "Aheadworks_Giftcard/js/model/product/giftcard": <?php echo $block->getJsGiftCardModelOptions() ?>,
            "Aheadworks_Giftcard/js/model/product/data": <?php echo $block->getJsProductData() ?>
        }
    }
    </script>
</div>
