<?php
/** @var \Aheadworks\Giftcard\Block\Giftcard\Codes */
?>
<?php if ($block->canShow()): ?>
<div id="aw-giftcard-codes-block" class="block">
    <div class="block-title">
        <h2><?php echo __('Your gift card codes') ?></h2>
    </div>
    <div class="block-content">
        <div class="box">
            <div class="box-content">
                <table>
                <?php foreach ($block->getGiftCardCodes() as $giftCardCode): ?>
                    <tr>
                        <td class="code"><?php echo $block->escapeHtml($giftCardCode->getCode()) ?></td>
                        <td class="balance"><?php echo $block->formatPrice($giftCardCode->getBalance()) ?></td>
                        <td class="action-apply"><a href="<?php echo $block->getApplyUrl($giftCardCode->getCode()) ?>"><?php echo __('Apply') ?></a></td>
                    </tr>
                <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>