<?php
/** @var \Aheadworks\Giftcard\Block\Giftcard\Info */
?>
<?php if ($block->getGiftCardStatusInfo()): ?>
    <div id="aw-giftcard-info-block" class="block">
        <div class="block-title">
            <h2><?php echo __('Gift Card Code Information') ?></h2>
        </div>
        <div class="block-content">
            <div class="box">
                <div class="box-content">
                    <table>
                        <tr>
                            <td class="label"><?php echo __('Code') ?></td>
                            <td><strong class="giftcard-code"><?php echo $block->getGiftCardStatusInfo()->getCode() ?></strong></td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo __('Availability') ?></td>
                            <td><strong class="giftcard-state"><?php echo $block->getGiftCardStatusInfo()->getStatus() ?> </strong></td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo __('Is Used') ?></td>
                            <td><strong class="giftcard-is_used"><?php echo $block->getGiftCardStatusInfo()->getIsUsed() ?> </strong></td>
                        </tr>
                        <tr>
                            <td class="label"><?php echo __('Balance') ?></td>
                            <td><strong><?php echo $block->getGiftCardStatusInfo()->getBalance() ?></strong></td>
                        </tr>
                        <?php if ($block->getGiftCardStatusInfo()->hasExpireAt()): ?>
                            <tr>
                                <td class="label"><?php echo __('Expires') ?></td>
                                <td><strong><?php echo $block->getGiftCardStatusInfo()->getExpireAt() ?></strong></td>
                            </tr>
                        <?php endif;?>
                    </table>
                </div>
            </div>
        </div>
    </div>
<?php endif;?>