<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \MemorialBracelets\IconOption\Block\Product\View\Options\Type\Icon $block */

$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required _required' : '';

if ($_option->getType() != 'iconpicker') return;

$pickerId = 'iconpicker-'.sha1(microtime(true).rand());

$icons = $block->getIcons();

/** @var \Magento\Framework\Pricing\Helper\Data $priceHelper */
$priceHelper = $this->helper(\Magento\Framework\Pricing\Helper\Data::class);
?>
<div class="admin__field field <?php /* @escapeNotVerified */ echo $class ?>">
    <label class="label admin__field-label" for="opt-sel-<?= $_option->getId(); ?>">
        <span><?php echo $block->escapeHtml($_option->getTitle()) ?></span>
    </label>

    <div class="control admin__field-control">
        <select id="opt-sel-<?= $_option->getId(); ?>" name="options[<?= $_option->getId(); ?>]" class="product-custom-option admin__control-select">
            <option value>-- Please Select --</option>
            <?php foreach($icons as $icon):
                $selected = $icon->getId() == $block->getDefaultValue();
                $price = $block->getFormattedIconPrice($icon);
                $priceString = floatval($block->getIconPrice($icon)) ? " (+ {$price})" : '';
            ?>
                <option value="<?= $icon->getId(); ?>" <?= $selected ? 'selected' : '' ?>>
                    <?= $icon->getTitle(); ?>
                    <?= $priceString ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
</div>
