<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;
// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

/** @var $compareHelper Magento\Catalog\Helper\Product\Compare */
$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');

/** @var $wishlistHelper Magento\Wishlist\Helper\Data */
$wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>

                        <!--Hide product swatch details-->
                        <?php /*echo $block->getProductDetailsHtml($_product); */?>

                        <!--new plp buttons-->
                        <div class="product-item-inner">
                            <?php $wishlistSubmitParams = $wishlistHelper->getAddParams($_product);
                            $applyChanges = false;
                            /** Check if product type is giftcard type. */
                            $isGiftcardType = ($_product->getData('type_id') == 'aw_giftcard') ? true : false;
                            if (isset($isGiftcardType) && $isGiftcardType) {
                                /** @var  $applyChanges, if product type is giftcard, set flag to apply style changes. */
                                $applyChanges = true;
                            }
                            ?>
                            <div class="buttons">
                                <a class="button btn button-customize" href="<?= $_product->getProductUrl() ?>"
                                ><?= ($applyChanges) ? __('Select Dollar Amount') : __('Customize'); ?></a>
                                <?php
                                    if (!$applyChanges) {
                                        echo '<div class="links">
                                            <a class="button btn button-compare" href="#" data-post='.$compareHelper->getPostDataParams($_product).'>
                                                <i class="icon-compare"></i>
                                                <span class="text">'.__('Compare').'</span>
                                            </a>
                                            <a class="button btn button-wish" href="#"
                                               data-post='.$wishlistSubmitParams.'
                                               data-action="add-to-wishlist">
                                                <i class="icon-wishlist"></i>
                                                <span class="text">'.__('Wishlist').'</span>
                                            </a>
                                        </div>';
                                    }
                                ?>
                            </div>
                        </div>

                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
