<?php
    /** @var  $optionHelper \MemorialBracelets\CheckHandling\Helper\Data */
    $optionHelper = $this->helper('MemorialBracelets\CheckHandling\Helper\Data');
?>
<?php /** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */ ?>
<?php $_item = $block->getItem() ?>
<?php $_order = $block->getItem()->getOrderItem()->getOrder() ?>
<?php
    //Remove the additional options since we don't want to display them here.
    $pOptions = $_item->getOrderItem()->getProductOptions();
    unset($pOptions['additional_options']);
    $_item->getOrderItem()->setProductOptions($pOptions);
?>
<tr id="order-item-row-<?php /* @escapeNotVerified */ echo $_item->getId() ?>">
    <td class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
        <strong class="product name product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?></strong>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?php echo $addInfoBlock->setItem($_item->getOrderItem())->toHtml(); ?>
        <?php endif; ?>
        <?php echo $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" data-th="<?php echo $block->escapeHtml(__('SKU')); ?>"><?php /* @escapeNotVerified */ echo $block->prepareSku($block->getSku()) ?></td>
    <td class="col price" data-th="<?php echo $block->escapeHtml(__('Price')); ?>">
        <?php echo $block->getItemPriceHtml(); ?>
    </td>
    <td class="col qty" data-th="<?php echo $block->escapeHtml(__('Qty Invoiced')); ?>">
        <span class="qty summary"><?php /* @escapeNotVerified */ echo $_item->getQty()*1 ?></span>
    </td>
    <td class="col subtotal" data-th="<?php echo $block->escapeHtml(__('Subtotal')); ?>">
        <?php echo $block->getItemRowTotalHtml(); ?>
    </td>
</tr>
<?php if ($_options = $block->getItemOptions()): ?>
    <?php if ($_item->getOrderItem()->getProductType() == 'aw_giftcard'):?>
        <?php
        //We don't need the giftcard design name.
        unset($_options[0]);
        ?>
        <?php foreach ($_options as $_option) : ?>
            <tr class="item-options" >
                <td class="col name" colspan="2">
                    <div style="font-weight: bold; float: left"><?php echo $block->escapeHtml($_option['label']) ?>: </div>
                    <span style="float: left;">&nbsp <?= $block->escapeHtml($_option['value']);?></span>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <?php foreach ($_options as $_option) : ?>
            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
            <?php if (isset($_formatedOptionValue['full_view']) || !empty($_formatedOptionValue['value'])): ?>
                <tr class="item-options" >
                    <td class="col name" colspan="2">
                        <div style="font-weight: bold; float: left"><?php echo $block->escapeHtml($_option['label']) ?>: </div>
                        <?php if (!$block->getPrintStatus()): ?>
                            <span style="float: left; margin-left: 5px;">
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <?= $_formatedOptionValue['full_view'] ?>
                                <?php else: ?>
                                    <?= $_formatedOptionValue['value'] ?>
                                <?php endif; ?>
                        </span>
                        <?php else: ?>
                            <span style="float: left; margin-left: 5px;">
                                <?php if($_option['option_type'] =='iconpicker' || $_option['option_type'] =='picker') : ?>
                                    <?php echo nl2br($block->escapeHtml($_option['value'])) ?>
                                <?php else : ?>
                                    <?php echo nl2br($block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value']))) ?>
                                <?php endif ?>
                        </span>
                        <?php endif; ?>
                    </td>
                    <td class="col price"><?= $optionHelper->getOptionPrice($_item->getOrderItem(), $_option) ?></td>
                    <td class="col qty">&nbsp;</td>
                    <td class="col subtotal">&nbsp;</td>
                </tr>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endif; ?>

