<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block newsletter">
    <div class="title"><strong>Newsletter</strong></div>
    <div class="content">
        <form class="form subscribe"
              novalidate
              action="http://oi.vresp.com?fid=e31dfb83b1"
              target="vr_optin_popup"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              onsubmit="window.open('http://www.verticalresponse.com', 'vr_optin_popup', 'scrollbars=yes,width=600,height=450');return true;"
              id="newsletter-validate-detail">
            <div class="field newsletter">
                <label class="label" for="newsletter"><span><?php /* @escapeNotVerified */ echo __('Sign Up for Our Newsletter:') ?></span></label>
                <div class="control">
                    <input name="email_address" type="email" id="newsletter"
                           placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                           data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                    <span><?php /* @escapeNotVerified */ echo __('Subscribe') ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
