<?php
    /** @var  $optionHelper \MemorialBracelets\CheckHandling\Helper\Data */
    $optionHelper = $this->helper('MemorialBracelets\CheckHandling\Helper\Data');
    /** @var $engravingHelper \MemorialBracelets\EngravingDisplay\Helper\Data */
    $engravingHelper = $this->helper('MemorialBracelets\EngravingDisplay\Helper\Data');

    $_item = $block->getItem();
    $pOptions = $_item->getOrderItem()->getProductOptions();
    unset($pOptions['additional_options']);

    //Add wording to engraving lines.
    if (isset($pOptions['options'])) {
        foreach ($pOptions['options'] as $k => $opt) {
            if ($opt['option_type'] == 'engraving') {
                $text = trim($opt['print_value']);
                $text .= "\n* " . $engravingHelper->getEngravingMessage();
                $opt['print_value'] = $text;
                $opt['value'] = $text;
                $pOptions['options'][$k] = $opt;
            }
        }
    }
    $_item->getOrderItem()->setProductOptions($pOptions);
?>
<?php $_order = $block->getItem()->getOrder(); ?>
<tr>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= /* @escapeNotVerified */  __('SKU'); ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
            <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="item-price">
        <?= /* @escapeNotVerified */  number_format($_item->getOrderItem()->getOriginalPrice(), 2); ?>
    </td>
    <td class="item-qty"><?= /* @escapeNotVerified */  $_item->getQty() * 1 ?></td>
    <td class="item-price">
        <?= /* @escapeNotVerified */  $block->getItemPrice($_item); ?>
    </td>
</tr>
<?php if ($block->getItemOptions()):?>
    <?php foreach ($block->getItemOptions() as $option): ?>
        <?php if (isset($option['value']) && !empty($option['value'])):?>
            <tr>
                <td>
                    <div><span style="font-weight: bold; float: left;"><?= $option['label']; ?>:&nbsp;</span>
                        <?php
                        $parts = preg_split('/\R/', $option['value']);
                        echo "<div style=\"float: left;\">";
                        foreach ($parts as $p) {
                            if (!empty($p)) {
                                echo "<span>".$p."</span><br>";
                            }
                        }
                        echo "</div>";
                        ?>
                    </div>
                </td>
                <td class="col price" style="text-align: right"><?= $optionHelper->getOptionPrice($_item->getOrderItem(), $option) ?></td>
                <td class="col qty">&nbsp;</td>
                <td class="col subtotal">&nbsp;</td>
            </tr>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>
