<?php
/** @var $block Aheadworks\Giftcard\Block\Checkout\Cart\Giftcard */
?>
<div class="block giftcard" id="cart-block-giftcard" data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
    <div class="title" data-role="title">
        <strong id="cart-block-giftcard-heading" role="heading" aria-level="2"><?php echo __('Gift Cards') ?></strong>
    </div>
    <div class="content" data-role="content" aria-labelledby="cart-block-giftcard-heading">
        <?php echo $block->getChildHtml('giftcard_codes') ?>
        <form id="aw-gc-code-form"
              action="<?php echo $block->getActionUrl() ?>"
              method="post"
              data-mage-init='{"aheadworksGCCode":<?php echo $block->getJsInitOptions() ?>}'>
            <div class="fieldset coupon">
                <div class="field">
                    <label for="giftcard_code" class="label"><span><?php echo __('Enter your gift card code') ?></span></label>
                    <div class="control">
                        <input type="text" class="input-text" id="<?php echo $block->getCodeInputId() ?>" name="giftcard_code" value="" placeholder="<?php echo $block->escapeHtml(__('Enter your gift card code'));?>" />
                    </div>
                </div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button class="action apply-giftcard primary" type="button" value="<?php echo __('Apply Gift Card Code') ?>">
                            <span><?php echo __('Apply Gift Card Code') ?></span>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
