<?php
/** @var $block \Aheadworks\Giftcard\Block\Customer\Giftcard */
?>
<?php echo $block->getChildHtml('giftcard_info') ?>
<?php echo $block->getChildHtml('giftcard_codes') ?>
<form id="form-validate"
      class="form form-aw-giftcard"
      action="<?php echo $block->getActionUrl() ?>"
      method="post"
      data-mage-init='{"aheadworksGCCode":<?php echo $block->getJsInitOptions() ?>}'
    >
    <fieldset class="fieldset check-giftcard">
        <?php echo $block->getBlockHtml('formkey')?>
        <div class="field required">
            <label class="label" for="giftcard_code"><span><?php echo __('Enter gift card code') ?></span></label>
            <div class="control">
                <input type="text" id="<?php echo $block->getCodeInputId() ?>" name="giftcard_code" value="" title="<?php echo __('Enter gift card code') ?>" class="input-text" data-validate="{required:true}">
            </div>
        </div>
        <input type="hidden" name="check" id="<?php echo $block->getCodeCheckInputId() ?>" value="1" />
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action primary check-giftcard" title="<?php echo __('Check Status and Balance') ?>"><span><?php echo __('Check Status and Balance') ?></span></button>
        </div>
    </div>
</form>