<?php
/** @var $block \Aheadworks\Giftcard\Block\Adminhtml\Product\Composite\Fieldset\Giftcard */
?>
<fieldset id="catalog_product_composite_configure_fields_aw_giftcard" class="fieldset admin__fieldset">
    <legend class="legend admin__legend">
        <span><?php echo __('Gift Card Options') ?></span>
    </legend>
    <?php if ($block->isFixedAmount()): ?>
        <input type="hidden" name="aw_gc_amount" value="<?php echo $block->getFixedAmount() ?>" />
    <?php else: ?>
        <?php if ($block->hasAmountOptions()): ?>
            <div class="field admin__field _required required">
                <label class="label admin__field-label" for="aw_gc_amount">
                    <span><?php echo __('Amount') ?></span>
                </label>
                <div class="control admin__field-control">
                    <select id="<?php echo $this->getAmountsSelectId() ?>" name="aw_gc_amount" class="required-entry aw-gc-amount-entry">
                        <?php echo $block->getAmountsOptionsHtml() ?>
                    </select>
                </div>
            </div>
        <?php else: ?>
            <input type="hidden" id="<?php echo $this->getAmountsSelectId() ?>" name="aw_gc_amount" value="custom" />
        <?php endif; ?>
        <?php if ($block->isAllowOpenAmount()): ?>
            <div class="field admin__field _required required" style="display: none;" data-show="custom">
                <label class="label admin__field-label" for="aw_gc_custom_amount">
                    <span><?php echo sprintf('%s %s', __('Amount in'), $block->getDisplayCurrencyCode()) ?></span>
                </label>
                <div class="control admin__field-control">
                    <input type="text"
                           id="aw_gc_custom_amount"
                           name="aw_gc_custom_amount"
                           value="<?php echo $block->getCustomAmountOptionValue() ?>"
                           class="validate-number required-entry input-text aw-gc-amount-entry aw-gc-min-amount aw-gc-max-amount"
                           data-min-value="<?php echo $block->convertPrice($block->getMinOpenAmount()) ?>"
                           data-max-value="<?php echo $block->convertPrice($block->getMaxOpenAmount()) ?>"
                           />
                    <div class="first">
                        <span><?php echo sprintf('%s %s', __('Minimum:'), $block->formatPrice($block->getMinOpenAmount())) ?></span>
                    </div>
                    <div class="last">
                        <span><?php echo sprintf('%s %s', __('Maximum:'), $block->formatPrice($block->getMaxOpenAmount())) ?></span>
                    </div>
                </div>
            </div>
            <?php endif; ?>
        <?php endif; ?>
    <?php if ($block->isAllowDesignSelect()): ?>
    <div class="field admin__field _required required">
        <label class="label admin__field-label" for="aw_gc_amount">
            <span><?php echo __('Select a design') ?></span>
        </label>
        <div class="control admin__field-control">
            <select name="aw_gc_template" class="required-entry aw-gc-amount-entry">
                <?php echo $block->getTemplatesOptionsHtml() ?>
            </select>
        </div>
    </div>
    <?php endif; ?>
    <?php if ($block->isSingleDesign()): ?>
        <input type="hidden" id="aw_gc_template" name="aw_gc_template" value="<?php echo $block->getTemplateValue(); ?>">
    <?php endif; ?>

    <div class="field admin__field _required required">
        <label class="label admin__field-label" for="aw_gc_sender_name">
            <span><?php echo __('Sender Name') ?></span>
        </label>
        <div class="control admin__field-control">
            <input type="text" name="aw_gc_sender_name" class="required-entry input-text" value="<?php echo $block->getSenderNameValue() ?>" />
        </div>
    </div>
    <?php if ($block->allowedEmail()): ?>
        <div class="field admin__field _required required">
            <label class="label admin__field-label" for="aw_gc_sender_email">
                <span><?php echo __('Sender Email') ?></span>
            </label>
            <div class="control admin__field-control">
                <input type="text" name="aw_gc_sender_email" class="required-entry input-text validate-email" value="<?php echo $block->getSenderEmailValue() ?>" />
            </div>
        </div>
    <?php endif; ?>
    <div class="field admin__field _required required">
        <label class="label admin__field-label" for="aw_gc_recipient_name">
            <span><?php echo __('Recipient Name') ?></span>
        </label>
        <div class="control admin__field-control">
            <input type="text" name="aw_gc_recipient_name" class="required-entry input-text" value="<?php echo $block->getRecipientNameValue() ?>" />
        </div>
    </div>
    <?php if ($block->allowedEmail()): ?>
        <div class="field admin__field _required required">
            <label class="label admin__field-label" for="aw_gc_recipient_email">
                <span><?php echo __('Recipient Email') ?></span>
            </label>
            <div class="control admin__field-control">
                <input type="text" name="aw_gc_recipient_email" class="required-entry input-text validate-email" value="<?php echo $block->getRecipientEmailValue() ?>" />
            </div>
        </div>
    <?php endif; ?>
    <?php if ($block->isAllowMessage()): ?>
        <div class="field admin__field">
            <label class="label admin__field-label" for="aw_gc_headline">
                <span><?php echo __('Headline') ?></span>
            </label>
            <div class="control admin__field-control">
                <input type="text" name="aw_gc_headline" class="input-text" value="<?php echo $block->getHeadlineValue() ?>" />
            </div>
        </div>
        <div class="field admin__field">
            <label class="label admin__field-label" for="aw_gc_message">
                <span><?php echo __('Message') ?></span>
            </label>
            <div class="control admin__field-control">
                <textarea name="aw_gc_message" class="input-text" cols="50" rows="3"><?php echo $block->getMessageValue() ?></textarea>
            </div>
        </div>
    <?php endif; ?>
    <script>
        require([
            'jquery',
            'aheadworksGCCompositeOptions'
        ], function($, giftCardCompositeOptions) {
            $(document).ready(function() {
                giftCardCompositeOptions(<?php echo $block->getJsInitOptions() ?>, $('#catalog_product_composite_configure_fields_aw_giftcard'));
            });
        });
    </script>
</fieldset>
