<?php
/** @var $block \Aheadworks\Giftcard\Block\Adminhtml\Product\Form\Renderer\GiftcardAmounts */
$element = $block->getElement();
$_htmlId = $block->getElement()->getHtmlId();
?>
<div class="field" id="attribute-<?php echo $_htmlId?>-container" data-attribute-code="<?php echo $_htmlId?>">
    <label class="label"><span><?php echo $block->getElement()->getLabel() ?></span></label>
    <div class="control">
        <table class="admin__control-table" id="<?php echo $block->getAmountsTableId() ?>">
            <thead>
                <tr>
                    <th><?php echo __('Web Site'); ?></th>
                    <th class="required"><?php echo __('Amount') ?></th>
                    <th class="col-delete"><?php echo __('Action') ?></th>
                </tr>
            </thead>
            <tbody id="<?php echo $block->getRowsContainerId(); ?>"></tbody>
            <tfoot>
                <tr>
                    <td colspan="3" class="col-actions-add"><?php echo $block->getAddButtonHtml() ?></td>
                </tr>
            </tfoot>
        </table>
        <table id="<?php echo $block->getAmountsErrorId() ?>" style="display: none;">
            <tr><td><label class="mage-error"></label></td></tr>
        </table>
        <?php echo $block->getJsInitScripts() ?>
    </div>
</div>
