<?php
/** @var $block Aheadworks\Giftcard\Block\Product\View */
?>
<?php if ($block->canRenderOptions()): ?>
    <?php
        $stepCount = 1;
    ?>
    <?php if ($block->isFixedAmount()): ?>
        <?php echo $block->getChildHtml('giftcard_price'); ?>
    <?php endif; ?>
    <div class="aw-gc-product-form-options" id="aw-gc-product-form-options" tabindex="0" data-bind="visible: sectionsShow" style="display: none">
        <fieldset class="fieldset">
            <?php if ($block->isFixedAmount()): ?>
                <input type="hidden" name="aw_gc_amount" value="<?php echo $block->getFixedAmount() ?>" />
            <?php else: ?>
                <legend class="legend"><span class="aw-gc-product-form-options__step-number"><?php echo $stepCount++ ?></span><span><?php echo __('Choose an amount') ?></span></legend>
                <div class="field required aw-gc-product-form-options__field-full-width">
                    <label class="label" for="aw_gc_amount">
                        <span><?php echo __('Card value') ?> (<?php echo $block->getDisplayCurrencySymbol() ?>)</span>
                    </label>

                    <div class="fieldset">
                        <div class="field aw-gc-product-form-options__amount-control" data-bind="visible: hasAmounts">
                            <div class="control amount-options" data-bind="if: hasAmounts">
                                <select name="aw_gc_amount" class="required-entry aw-gc-amount-entry"
                                        data-bind="options: amounts,
                                                   optionsCaption: '<?php echo __('Choose an Amount...') ?>',
                                                   optionsValue: 'value',
                                                   optionsText: 'label',
                                                   value: amount"></select>
                            </div>

                            <div class="control amount-options" data-bind="ifnot: hasAmounts, visible: !hasAmounts">
                                <input type="hidden" name="aw_gc_amount" value="custom"/>
                            </div>
                        </div>

                        <div class="field aw-gc-product-form-options__amount-control">
                            <div class="control amount-custom"
                                 style="display: none;"
                                 data-bind="visible: isCustomAmount, if: allowCustomAmount"
                                 >
                                 <input type="text" name="aw_gc_custom_amount" value=""
                                        class="validate-number required-entry input-text aw-gc-amount-entry aw-gc-min-amount aw-gc-max-amount"
                                        data-bind="attr: {min_value: minCustomAmountValue, max_value: maxCustomAmountValue, placeholder: customAmountHint},
                                                  value: amountCustom" maxlength="4"/>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        </fieldset>

        <?php if ($block->isAllowDesignSelect()): ?>
        <fieldset class="fieldset">
            <legend class="legend"><span class="aw-gc-product-form-options__step-number"><?php echo $stepCount++ ?></span><span><?php echo __('Select a design') ?></span></legend>

            <div class="field required aw-gc-product-form-options__field-full-width">
                <div class="control aw-gc-product-form-options__template-options" data-bind="foreach: templates" data-highlight="aw_gc_template">
                    <a href="#" class="aw-gc-product-form-options__template-option"
                       data-bind="event: {click: function(data, event) { $parent.templateSelect(value); }},
                                  css: {selected: value == $parent.templateValue(), empty: !imageUrl}"
                        >
                        <img class="aw-gc-product-form-options__template-image" data-bind="attr: {src: imageUrl}" src="" alt="" />
                        <!-- ko ifnot: imageUrl -->
                        <span class="aw-gc-product-form-options__template-name" data-bind="text: name"></span>
                        <!-- /ko -->
                    </a>
                </div>
                <div class="control aw-gc-product-form-options__template-value hidden">
                    <input type="hidden" id="aw_gc_template" name="aw_gc_template" data-bind="value: templateValue" value="" class="required-entry">
                </div>
            </div>
        </fieldset>
        <?php endif; ?>

        <?php if ($block->isSingleDesign()): ?>
            <input type="hidden" id="aw_gc_template" name="aw_gc_template" value="<?php echo $block->getTemplateValue(); ?>">
        <?php endif; ?>

        <fieldset class="fieldset">
            <legend class="legend"><span class="aw-gc-product-form-options__step-number"><?php echo $stepCount++ ?></span><span><?php echo __('Enter recipient name and either your email address for delivering printed gift card or the recipient’s email address for sending electronically.') ?></span></legend>
            <div>
                <div class="email fromto">
                    <div class="fieldset">
                        <div class="field required aw-gc-product-form-options__fromto">
                            <label class="label fromto" for="aw_gc_recipient_name">
                                <span><?php echo __('To') ?></span>
                            </label>

                            <div class="control fromto-name">
                                <input type="text" name="aw_gc_recipient_name" placeholder="<?php echo __('Recipient Name') ?>" class="required-entry input-text" value="" data-bind="value: recipientName" />
                            </div>

                            <?php if ($block->allowedEmail()): ?>
                                <div class="control fromto-email aw-gc-product-form-options__email">
                                    <input type="text" name="aw_gc_recipient_email" placeholder="<?php echo __('Recipient Email') ?>" class="required-entry input-text validate-email" value="" data-bind="value: recipientEmail" />
                                </div>
                            <?php endif; ?>
                        </div>

                        <div class="field required aw-gc-product-form-options__fromto" data-bind="ifnot: isLoggedIn">
                            <label class="label fromto" for="aw_gc_recipient_name">
                                <span><?php echo __('From') ?></span>
                            </label>

                            <div class="control fromto-name">
                                <input type="text" name="aw_gc_sender_name" placeholder="<?php echo __('Sender Name') ?>" class="required-entry input-text" value="" data-bind="value: senderName" />
                            </div>

                            <?php if ($block->allowedEmail()): ?>
                                <div class="control fromto-email aw-gc-product-form-options__email">
                                    <input type="text" name="aw_gc_sender_email" placeholder="<?php echo __('Sender Email') ?>" class="required-entry input-text validate-email" value="" data-bind="value: senderEmail" />
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>

                <?php if ($block->isAllowMessage()): ?>
                    <div class="email body aw-gc-product-form-options__email-content">
                        <div class="fieldset">
                            <div class="field aw-gc-product-form-options__field-full-width">
                                <label class="label" for="aw_gc_headline">
                                    <span><?php echo __('Headline') ?></span>
                                </label>

                                <div class="control headline">
                                    <input type="text" name="aw_gc_headline" placeholder="<?php echo __('Enter your headline here (optional)') ?>" class="input-text" value="" data-bind="value: headline" />
                                </div>
                            </div>

                            <div class="field aw-gc-product-form-options__field-full-width">
                                <label class="label" for="aw_gc_message">
                                    <span><?php echo __('Message') ?></span>
                                </label>

                                <div class="control message">
                                    <textarea name="aw_gc_message" placeholder="<?php echo __('Enter your gift card message here (optional)') ?>" class="input-text" cols="5" rows="5" data-bind="text: message"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>

                <?php if ($block->isAllowPreview()): ?>
                    <div class="aw-gc-product-form-options__preview">
                        <button type="button" class="action" data-bind="event: {click: function(data, event) { previewClick('<?php echo $block->getPreviewUrl() ?>', '#product_addtocart_form', '#aw-gc-product-preview-popup'); }}"><?php echo __('Preview') ?></button>
                    </div>
                <?php endif; ?>
            </div>
        </fieldset>
        <!-- todo: product recommendations in future-->
        <!--<fieldset class="fieldset">
            <legend class="legend"><span class="aw-gc-product-form-options__step-number"><?php echo $stepCount++ ?></span><span><?php echo __('Product recommendations (optional)') ?></span></legend>
        </fieldset>-->
    </div>
<?php else: ?>
    <?php echo $block->getChildHtml('giftcard_price'); ?>
<?php endif; ?>

<div id="aw-gc-product-preview-popup" title="Gift Card Preview" style="display: none;"></div>
