<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * New Customer block template
 *
 * @var $block \Magento\Customer\Block\Form\Login\Info
 */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer">
    <div class="title-wrapper">
        <div class="block-title">
            <strong id="block-new-customer-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo
                __('Create an Account') ?></strong>
        </div>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <?php /** Here we call the CMS static block for the create account content. */ ?>
        <?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('login-create-content')->toHtml() ?>
        <div class="actions-toolbar">
            <div class="primary">
                <a href="<?php /* @escapeNotVerified */ echo $block->getCreateAccountUrl() ?>"
                   class="action create primary">
                    <span><?php /* @escapeNotVerified */ echo __('Get Started') ?></span>
                </a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
